blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.AboutPageView.as_view(), name='about'),
    path('contact', views.ContactPageView.as_view(), name='contact'),
    path('send', views.send, name='send'),
    path ('post/<str:pk>', views.post, name='post'),
]

patrickBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Message(models.Model):
    email = models.EmailField(max_length=50)
    date = models.DateTimeField(default=datetime.now, blank=True)

class Post(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    title = models.CharField(max_length=1000)
    body = models.CharField(max_length=100000)
    created_at = models.DateTimeField(default=datetime.now, blank=True)

blog/views.py
from django.views.generic import TemplateView
from .models import Message, Post
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
import datetime
# Create your views here.

def home(request):
    posts = Post.objects.all()
   
    return render(request, 'index.html', {'posts': posts})

class AboutPageView(TemplateView):
    template_name = 'about.html'


class ContactPageView(TemplateView):
    template_name = 'contact.html'


def send(request):
    email = request.POST['email']

    user= Message.objects.create(email=email)
    user.save()
    messages.add_message(request, messages.INFO, 'Subscription successful')
    return redirect("blog:home")
    


def post(request, pk):
    posts = Post.objects.get(id=pk)
    return render(request, 'posts.html', {'posts': posts})

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PATRICK</title>
    {% load static %}
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static './css/all.css'%}">
    <!-- --------- Owl-Carousel -'%}------------------>
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css'%}">

    <!-- ------------ AOS Library ------------------------- -->
    <link rel="stylesheet" href="{% static './css/aos.css'%}">

    <!-- Custom Style   -->
    <link rel="stylesheet" href="{% static './css/Style.css'%}">

</head>

<body>

    <!-- ----------------------------  Navigation ---------------------------------------------- -->

    <nav class="nav">
        <div class="nav-menu flex-row">
            <div class="nav-brand">
                <a href="#"><span class="pat"> PATRICK</span> BLOG</a>
            </div>
            <div class="toggle-collapse">
                <div class="toggle-icons">
                    <i class="fas fa-bars"></i>
                </div>
            </div>
            <div>
                <ul class="nav-items">
                    <li class="nav-link">
                        <a href="{%url 'blog:home'%}">Home</a>
                    </li>
                    <li class="nav-link">
                        <a href="#">Category</a>
                    </li>
                    <li class="nav-link">
                        <a href="{%url 'blog:about'%}">About Us</a>
                    </li>
                    <li class="nav-link">
                        <a href="{%url 'blog:contact'%}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="social text-gray">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </nav>

    

    <section id="main">
        <div class="container">
            <article id="main-col">
                <h1 class="page-title">About Us</h1>
                <p>
                    Ghana’s leading online news publication mainly on health issues and <br> 
                    other matters such as politics, entertainment, <br>
                    technology and many more in West Africa and around the continent.
                </p>
                <p class="dark">
                    
                </p>
            </article>
            <aside id="sidebar">
                <div class="dark">
                    <h3> What We Do</h3>
                    <p>
                        we bring to your door step the latest trending all over the world expecially Ghana,
                    </p>
                </div>
            </aside>
        </div>
    </section>
<footer class="footer">
    <div class="container">
        <div class="about-us" data-aos="fade-right" data-aos-delay="200">
            <h2>About us</h2>
            <p>Ghana’s leading online news publication mainly on health issues and other matters such as politics, entertainment,
            technology and many more in West Africa and around the continent.</p>
        </div>
        <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
            <h2>Newsletter</h2>
            <p>Stay update with our latest</p>
            <div class="form-element">
                <input type="text" placeholder="Email"><span><i class="fas fa-chevron-right"></i></span>
            </div>
        </div>
        <div class="instagram" data-aos="fade-left" data-aos-delay="200">
            <h2>Instagram</h2>
            <div class="flex-row">
                <img src="{% static './assets/instagram/thumb-card3.png'%}" alt="insta1">
                <img src="{% static './assets/instagram/thumb-card4.png'%}" alt="insta2">
                <img src="{% static './assets/instagram/thumb-card5.png'%}" alt="insta3">
            </div>
            <div class="flex-row">
                <img src="{% static './assets/instagram/thumb-card6.png'%}" alt="insta4">
                <img src="{% static './assets/instagram/thumb-card7.png'%}" alt="insta5">
                <img src="{% static './assets/instagram/thumb-card8.png'%}" alt="insta6">
            </div>
        </div>
        <div class="follow" data-aos="fade-left" data-aos-delay="200">
            <h2>Follow us</h2>
            <p>Let us be Social</p>
            <div>
                <i class="fab fa-facebook-f"></i>
                <i class="fab fa-twitter"></i>
                <i class="fab fa-instagram"></i>
                <i class="fab fa-youtube"></i>
            </div>
        </div>
    </div>
    <div class="rights flex-row">
        <h4 class="text-gray">
            Copyright ©2021 All rights reserved | PATRICK BLOG
        </h4>
    </div>
    <div class="move-up">
        <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
    </div>
</footer>

<!-- -------------x------------- Footer --------------------x------------------- -->

<!-- Jquery Library file -->
<script src="{% static './js/Jquery3.4.1.min.js'%}"></script>

<!-- --------- Owl-Carousel js ------------------->
<script src="{% static './js/owl.carousel.min.js'%}"></script>

<!-- ------------ AOS js Library  ------------------------- -->
<script src="{% static './js/aos.js'%}"></script>

<!-- Custom Javascript file -->
<script src="{% static './js/main.js'%}"></script>
</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PATRICK</title>
    {% load static %}
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static './css/all.css'%}">


    <!-- --------- Owl-Carousel ------------------->
    <link rel="stylesheet" href="{% static './css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static './css/owl.theme.default.min.css'%}">

    <!-- ------------ AOS Library ------------------------- -->
    <link rel="stylesheet" href="{% static './css/aos.css'%}">

    <!-- Custom Style   -->
    <link rel="stylesheet" href="{% static './css/Style.css'%}">

</head>

<body>

    <!-- ----------------------------  Navigation ---------------------------------------------- -->

    <nav class="nav">
        <div class="nav-menu flex-row">
            <div class="nav-brand">
                <a href="#"><span class="pat"> PATRICK</span> BLOG</a>
            </div>
            <div class="toggle-collapse">
                <div class="toggle-icons">
                    <i class="fas fa-bars"></i>
                </div>
            </div>
            <div>
                <ul class="nav-items">
                    <li class="nav-link">
                        <a href="{%url 'blog:home'%}">Home</a>
                    </li>
                    <li class="nav-link">
                        <a href="#">Category</a>
                    </li>
                    <li class="nav-link">
                        <a href="{%url 'blog:about'%}">About Us</a>
                    </li>
                    <li class="nav-link">
                        <a href="{%url 'blog:contact'%}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="social text-gray">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </nav>
     <section class="contact" id="contact">

        <div class="row">

            <div class="content">

                <h3 class="title">contact info</h3>

                <div class="info">
                    <h3> <i class="fas fa-envelope"></i> patassuah@gmail.com </h3>
                    <h3> <i class="fas fa-phone"></i> +233-547-299-207 </h3>
                    <h3> <i class="fas fa-phone"></i> +233-591-776-950 </h3>
                    <h3> <i class="fas fa-map-marker-alt"></i> Ehi, Esiama, Ghana </h3>
                </div>

            </div>

        </div>

    </section>
    
    </div>

    <footer class="footer">
        <div class="container">
            <div class="about-us" data-aos="fade-right" data-aos-delay="200">
                <h2>About us</h2>
                <p>  Ghana’s leading online news publication  mainly on health issues and other matters such as politics, entertainment, technology and many more in West Africa and around the continent.</p>
            </div>
            <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
                <h2>Newsletter</h2>
                <p>Stay update with our latest</p>
                <div class="form-element">
                    <input type="text" placeholder="Email"><span><i class="fas fa-chevron-right"></i></span>
                </div>
            </div>
            <div class="instagram" data-aos="fade-left" data-aos-delay="200">
                <h2>Instagram</h2>
                <div class="flex-row">
                    <img src="{% static './assets/instagram/thumb-card3.png'%}" alt="insta1">
                    <img src="{% static './assets/instagram/thumb-card4.png'%}" alt="insta2">
                    <img src="{% static './assets/instagram/thumb-card5.png'%}" alt="insta3">
                </div>
                <div class="flex-row">
                    <img src="{% static './assets/instagram/thumb-card6.png'%}" alt="insta4">
                    <img src="{% static './assets/instagram/thumb-card7.png'%}" alt="insta5">
                    <img src="{% static './assets/instagram/thumb-card8.png'%}" alt="insta6">
                </div>
            </div>
            <div class="follow" data-aos="fade-left" data-aos-delay="200">
                <h2>Follow us</h2>
                <p>Let us be Social</p>
                <div>
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
        <div class="rights flex-row">
            <h4 class="text">
                Copyright ©2021 All rights reserved | PATRICK BLOG
            </h4>
        </div>
        <div class="move-up">
            <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
        </div>
    </footer>

    <!-- -------------x------------- Footer --------------------x------------------- -->

    <!-- Jquery Library file -->
    <script src="{% static './js/Jquery3.4.1.min.js'%}"></script>

    <!-- --------- Owl-Carousel js ------------------->
    <script src="{% static './js/owl.carousel.min.js'%}"></script>

    <!-- ------------ AOS js Library  ------------------------- -->
    <script src="{% static './js/aos.js'%}"></script>

    <!-- Custom Javascript file -->
    <script src="{% static './js/main.js'%}"></script>
</body>

</html>

templates/posts.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial;
            padding: 20px;
            background: #f1f1f1;
        }
        h2{
            color: #e8491d;
        }

        .header {
            padding: 2px;
            font-size: 40px;
            text-align: center;
            background: white;
        }

        .leftcolumn {
            float: left;
            width: 100%;
        }

        .card {
            background-color: white;
            padding: 20px;
            margin-top: 20px;
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        @media screen and (max-width: 800px) {

            .leftcolumn,
            .rightcolumn {
                width: 100%;
                padding: 0;
            }
        }
    </style>
</head>

<body>

    <div class="header">
        <h2>Patrick's Blog</h2>
    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="card">
                <div class="post-image"><img src="{{post.image.url}}" class="img" alt=""></div>
                <h1>{{posts.title}}</h1>
                <h5>{{posts.created_at|date:"m, d, Y"}}</h5>
                <p>{{posts.body}}</p>
            </div>
        </div>
    </div>

</body>
</html>